### ISSUE TITLE
Gumshoedb router doesn't properly handle errors returned by shards

### ISSUE THREAD

**Issue by mikejquinn** [philc/gumshoedb#9]
If a shard returns an error message, the router currently attempts to parse the error message as JSON - then passes the failed JSON parsing error down to the client.

For example, attempting a query which filters on a numeric dimension using a string value, a single shard will return this response:

        need a numeric value to filter column "foo"; got 0

However, the router will try to parse that string as JSON and instead return:

        invalid character 'e' in literal null (expecting 'u')

**Comment by cespare** [comment]
Whoops.

**Comment by cespare** [comment]
Also looks like a bad error to begin with (0 *is* a numeric value...maybe it's supposed to say "string").

**Comment by mikejquinn** [comment]
Ah, its a confusing example. I made the query with the string "0", so its just printing that. Both the value and passed data type would be helpful.

**Comment by cespare** [comment]
I still don't understand. Do you mean you tried to filter a *numeric* dimension with a *string* value?

**Comment by mikejquinn** [comment]
Correct.

**Comment by mikejquinn** [comment]
Ah, correct - sorry those were swapped in my description.

**Comment by mikejquinn** [comment]
Fixed.

**Comment by cespare** [comment]
OK I understand now. I'm not going to show the type for now because it might be more confusing than helpful to show the Go type (e.g. showing `float64` when you passed `0`.) I'm hoping to do a better cleanup of types later anyway.

Fixing the router issue now.

**Comment by cespare** [comment]
OK fixed.
